### ISSUE TITLE
offset parameter not working for `get_data_by_offset()`

### ISSUE THREAD

**Issue by ries9112** [GearPlug/octoparse-python#1]
Thank you for making this package!

I am having issues getting the 'OFFSET' parameter to work for `get_data_by_offset()`. Things seem to work fine outside of the offset parameter, but if I change that one to a different value it doesn't seem to have any effect on the data returned and it is not properly skipping/offsetting by the number of rows specified.

**Comment by ingmferrer** [comment]
Hello, sorry but this library is unmaintained and soon will be archived.
